CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE event_categories
(
    event_id VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL
);

CREATE TABLE event_occurrences
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   VARCHAR(150)                            NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    position   INTEGER,
    CONSTRAINT pk_event_occurrences PRIMARY KEY (id)
);

CREATE TABLE events
(
    id                    VARCHAR(150) NOT NULL,
    source_event_id       BIGINT,
    title                 VARCHAR(500) NOT NULL,
    description           TEXT,
    url                   VARCHAR(2048),
    start_date            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date              TIMESTAMP WITHOUT TIME ZONE,
    source_updated_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    version               BIGINT       NOT NULL,
    venue_name            VARCHAR(500),
    street                VARCHAR(500),
    zipcode               VARCHAR(20),
    city                  VARCHAR(150),
    latitude              DOUBLE PRECISION,
    longitude             DOUBLE PRECISION,
    wheelchair_accessible BOOLEAN,
    blind_accessible      BOOLEAN,
    deaf_accessible       BOOLEAN,
    sign_language         VARCHAR(500),
    mental_accessibility  VARCHAR(500),
    price_type            VARCHAR(100),
    price_detail          TEXT,
    access_type           VARCHAR(100),
    booking_url           VARCHAR(2048),
    booking_link_text     VARCHAR(500),
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

ALTER TABLE events
    ADD CONSTRAINT uc_events_source_event UNIQUE (source_event_id);

CREATE INDEX idx_events_city ON events (city);

CREATE INDEX idx_events_end_date ON events (end_date);

CREATE INDEX idx_events_source_updated_at ON events (source_updated_at);

CREATE INDEX idx_events_start_date ON events (start_date);

CREATE INDEX idx_events_zipcode ON events (zipcode);

CREATE INDEX idx_occurrences_start_date ON event_occurrences (start_date);

ALTER TABLE event_occurrences
    ADD CONSTRAINT FK_OCCURRENCES_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

CREATE INDEX idx_occurrences_event ON event_occurrences (event_id);

ALTER TABLE event_categories
    ADD CONSTRAINT fk_event_categories_event FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);