ALTER TABLE events
    ADD COLUMN slug VARCHAR(220),
    ADD COLUMN image_url VARCHAR(2048),
    ADD COLUMN image_alt VARCHAR(1000);

UPDATE events
SET slug = COALESCE(
        NULLIF(
                regexp_replace(
                        regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g'),
                        '(^-+|-+$)',
                        '',
                        'g'
                ),
                ''
        ),
        'event'
    ) || '-' || substring(md5(id) from 1 for 8)
WHERE slug IS NULL;

ALTER TABLE events
    ALTER COLUMN slug SET NOT NULL;

CREATE UNIQUE INDEX uc_events_slug ON events (slug);

CREATE TABLE feedback_submissions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(50)                             NOT NULL,
    message    TEXT                                    NOT NULL,
    email      VARCHAR(320),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_feedback_submissions PRIMARY KEY (id)
);

CREATE INDEX idx_feedback_created_at ON feedback_submissions (created_at);

CREATE TABLE event_reports
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_slug VARCHAR(220)                            NOT NULL,
    type       VARCHAR(50)                             NOT NULL,
    message    TEXT,
    email      VARCHAR(320),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_event_reports PRIMARY KEY (id)
);

CREATE INDEX idx_event_reports_event_slug ON event_reports (event_slug);
CREATE INDEX idx_event_reports_created_at ON event_reports (created_at);
